export enum TypePokemonEnum {
    NONE = "None",
    GRASS = "Grass",
    FIRE = "Fire",
    WATER = "Water",
    GROUND = "Ground",
    ROCK = "Rock",
    FAIRY = "Fairy",
    PSYCHIC = "Psychic",
    BUG = "Bug",
    DRAGON = "Dragon",
    DARK = "Dark",
    FIGHTING = "Fighting",
    ICE = "Ice",
    STEEL = "Steel",
    NORMAL = "Normal",
    POISON = "Poison",
    ELECTRIC = "Electric",
    GHOST = "Ghost",
    FLYING = "Flying",
}